theme: jekyll-theme-minimal
exclude: ["ReadMe.md", "Rakefile", "License.md"]

title: Leveraging Social Media to Understand Public Perception of the COVID-19 Pandemic
author: Sameh Saleh
email: sameh.n.saleh@gmail.com
github: ssaleh2
twitter: sameh_n_saleh

