theme: jekyll-theme-minimal
exclude: ["ReadMe.md", "Rakefile", "License.md"]

title: A Twitter Analysis of the 2019-nCoV
author: Sameh Saleh
email: sameh.n.saleh@gmail.com
github: ssaleh2
twitter: sameh_n_saleh

